name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: "Mostrando variables por defecto"
        run: echo "Evento:${{toJson(github.event)}}"