name: Deployment Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    env:
      username: ${{secrets.USER_NAME}}
      password: ${{secrets.PASSWORD}}

    runs-on: ubuntu-latest

    steps:
      - name: Mostrando variables por defecto
        run: |
          echo "Evento: ${{toJSON(github.event)}}"

      - name: Mostrando nombre autor
        run: |
          echo "Evento: ${{toJSON(github.event.head_commit.author.name)}}"
          echo "Github_Actor: $GITHUB_ACTOR"

      - name: Mostrando valores si usuario existe
        if: ${{ env.username != '' && env.password != '' }}
        run: echo "Si existe usuario y contraseña"

      - name: Versión del proyecto
        run: |
          echo "version: ${{ vars.PROJECT_VERSION }}"
