name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrando variables por defecto
        run: |
          echo "Evento: ${{toJSON(github.event)}}"

      - name: Mostrando nombre autor
        run: |
          echo "Evento: ${{toJSON(github.event.head_commit.author.name)}}"
          echo "Github_Actor: $GITHUB_ACTOR"
